version: '3.5'

services:

  rest-api-php:
    ports:
      - "${APP_HTTP_PORT}:80"
    volumes:
      - .:/var/www/html
    build: .
    command: php -S rest-api-php:80 -t public
    restart: always

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    platform: ${PLATFORM}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}